name: Run spark job

on:
  push:
    branches:
        - master
    paths:
      - 'src/spark_template/**'  # Specify the path to the directory of interest

jobs:
  detect-pushed-files:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          echo "THIS RUNS" > ../test



# jobs:
#   custom-command:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Custom Command
#         run: |
#           # Replace this with the command you want to run
#           echo "Running custom command"


#           name: Detect Pushed Files in /src/spark_template
