name: Run spark job

on:
  push:
    branches:
        - master
    paths:
      - 'src/spark_template/**'  # Specify the path to the directory of interest

jobs:
  submit-jobs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: 'kubectl exec -it spark-driver-ss-0 sh -c /opt/spark/workspace/submit-jobs.sh'
